### ISSUE TITLE
cannot run example with python 3.10 and pytorch1.11 in a virtual environment

### ISSUE THREAD

**Issue by gmarcusm** [IDSIA/lmtool-fwms#1]
I cannot run the provided example. The code depends on a very old version of pytorch (1.4), I had to install 1.11, and tried to run it inside a python virtual environment. This however seems to be preventing the import of the jit compiled module, and I get instead these errors:

```
     Loading extension module fast_weight_forward... 
Traceback (most recent call last):
  File "<...redacted>/lmtool-fwp/src/train.py", line 18, in <module>
    from model_main import MemTransformerLM
  File "<...redacted>/lmtool-fwp/src/model_main.py", line 19, in <module>
    from utils.cuda_fast_weight_layer import CudaFastWeightLinearTransformerLayer
  File "<...redacted>/lmtool-fwp/src/utils/cuda_fast_weight_layer.py", line 9, in <module>
    from utils.fast_fast_weight import fast_weight_delta
  File "<...redacted>/lmtool-fwp/src/utils/fast_fast_weight/__init__.py", line 17, in <module>
    mod_causal_dot_product_cuda = load(
  File "<...redacted>/lmtool-fwp/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "<...redacted>/lmtool-fwp/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1382, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "<...redacted>/lmtool-fwp/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1776, in _import_module_from_library
    assert isinstance(spec.loader, importlib.abc.Loader)
AttributeError: module 'importlib' has no attribute 'abc'. Did you mean: '_abc'?
```

Do you have any insight on how to proceed?

**Comment by kazuki-irie** [comment]
Thank you for your interest in our work!

> The code depends on a very old version of pytorch (1.4)

On my end, the code runs using Python 3.11 and PyTorch 2.0.1+cu117.

So unless you absolutely need Python 3.10 and PyTorch 1.11, one potential solution could be to update PyTorch.

**Comment by gmarcusm** [comment]
thanks for the prompt reply. I could get it to work with the python 3.8.10 and torch 2.0.1
